name = "glTF"
grammar = "json"
path_suffixes = ["gltf"]
tab_size = 2
autoclose_before = ",:]}"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
