[package]
name = "model_viewer_3d"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"
description = "Zed extension helper and companion 3D model viewer."
repository = "https://github.com/imboni/zed-gltf-model-viewer"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
